apt install python
pip install requests
pip install datetime
pip install sys
pip install time
pip install argparse
pip install os 
pip install colorama 
pip install csv  
pip install json 
pip install vk
pip install random
pip install colorama
pip install init
pip install colorama
pip install Fore
pip install Back
pip install Style
pip install itertools
pip install threading
pip install time
pip install base64
pip install urllib.request
pip install bs4 
pip install BeautifulSoup4
pip install socket
apt install toilet